# Generated by Django 5.1.6 on 2025-02-20 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_tag_recipe_category_comment_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='nutritional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
